name: project_environment
dependencies:
  - python=3.9
  - pip:
      - monai[nibabel]>=1.3.0
      - monai-generative==0.2.3
      - numpy>=1.26
      - torch>=1.8
      - torchvision>=0.17
      - matplotlib
      - tqdm
      - wandb
      - plotly
      - pandas
  - pip
channels:
  - anaconda
  - conda-forge
